# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('ipv4', models.CharField(max_length=15)),
                ('ipv6', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('enabled', models.BooleanField(default=True)),
                ('types', models.CharField(choices=[('DNS', 'DNS'), ('WEB', 'WEB'), ('DB', 'DB'), ('APP', 'APP')], max_length=15)),
                ('created', models.DateField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.OperatingSystem')),
            ],
        ),
    ]
